### NOTE:
# Updated GitHub Actions to Node.js 24-compatible versions:
# actions/checkout: v4 → v5
# actions/setup-python: v5 → v6
# Reason: Node.js 20 deprecation warning.


name: Naukri Job Bot

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Run bot
        run: python src/main.py


        
